server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/